// action types
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const ISSUE_CREATED = "ISSUE_CREATED";
export const ISSUE_CREATED_DONE = "ISSUE_CREATED_DONE";
export const NOTIFICATION_CREATED = "NOTIFICATION_CREATED";
export const NOTIFICATION_REMOVED = "NOTIFICATION_REMOVED";
